### ISSUE TITLE
Send notices to channel based on command used by user

### ISSUE THREAD

**Issue by xhoogland** [LVPlayground/bot-nuwani#2]
Since smartphones with IRC are a lot used nowadays there is some annoying issue for at least AndChat and AndroIRC-users. In those cases every notice from a sister causes a new PM in a seperate window. So having Nuwani + 8 sisters can give you 9 PMs with unreadable admin-notices and/or -conversations.

It would be nice if people could switch with a command like !adminmsgs [notice/channel] but I do see some flaws in here, perhaps only from 1 specific sister... I'll poke around and write some more about this tomorrow!

**Comment by ghost** [comment]
I can confirm this - I use the AndroIRC app on my phone, and it's rather annoying to have all the different query windows for each of the Nuwani sisters. I grabbed a quick screenshot:

![mifl2dj](https://cloud.githubusercontent.com/assets/15123289/14231259/12471bcc-f974-11e5-9954-8a9e559b6cb7.png)

**Comment by debuggest3** [comment]
This is actually caused by the IRC clients not implementing the IRC protocol properly. What Nuwani does, is sending the following IRC message:

`PRIVMSG %#LVP.echo :*** Mr_teo (Id:15) has signed up for /waterfight.`

The problem for these IRC clients is in the "%#LVP.echo" bit. This bit means that the message should be sent to all people in #LVP.echo with %-rights (that is half-op, or +h) or higher. However, the aforementioned IRC clients do not recognize this syntax and simply try to find a channel named "%#LVP.echo", which doesn't exist. The clients will then fall back to assuming that it is a private message and create a separate messaging window with these messages.

While I understand that it is annoying for users of these IRC clients, it is not something that is practical to change within Nuwani. This is because a change will affect all users in #LVP.echo with %-rights or higher (i.e. all administrators and management), even users with IRC client that do implement the IRC protocol properly.

What I do suggest is sending a message to the maintainer of the IRC client and asking them to change the behavior to match the IRC protocol.

**Comment by xhoogland** [comment]
Since I kinda had this feeling, I tweeted both AndChat and AndroIRC about where to report bugs for them. Although I'm afraid I won't get any answers, AndChat is afaik unsupported and AndroIRC closed every URL/link to their support, I hope I do get some results. Neither of them are afaik open source.

In the worst case scenario there should be something done in Nuwani if you ask me, despite it doesn't have a high priority and with the realisation that it has a huge impact on code perhaps.

**Comment by ghost** [comment]
@Xanland - There's email addresses listed on these pages which you could try:

https://play.google.com/store/apps/details?id=net.andchat&hl=en_GB
https://play.google.com/store/apps/details?id=com.androirc&hl=en_GB

**Comment by ghost** [comment]
I can confirm this is specific to those IRC apps. I've switched to this: https://play.google.com/store/apps/details?id=com.irccloud.android

Working flawlessly so far, no issues with Nuwani either!

**Comment by xhoogland** [comment]
Expected that indeed, nice find!

Note to self: Still contact andchat and androirc, but don't expect anything. :+
